// <auto-generated />
using System;
using DevDynamics.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DevDynamics.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260425091637_AddCompany")]
    partial class AddCompany
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.26");

            modelBuilder.Entity("DevDynamics.API.Models.DevActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Commits")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Contributor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Documentation")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Meetings")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Merges")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PRMergedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PROpenedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("PullRequests")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DevActivities");
                });
#pragma warning restore 612, 618
        }
    }
}
